### ISSUE TITLE
resolv.conf needs option trust-ad in order for glibc to trust it

### ISSUE THREAD

**Issue by Mikaela** [NLnetLabs/dnssec-trigger#5]
Unless `/etc/resolv.conf` contains `trust-ad` in `options`, glibc using applications aren't going to see that DNSSEC validation is successful. This affects at least OpenSSH client with `VerifyHostKeyDNS yes` option.

* https://gnutoolchain-gerrit.osci.io/r/c/glibc/+/461

I am using version 0.17+repack-3+b1 on Debian Testing and while I found a [Debian bug report on this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965938), there are no comments and I think it should be fixed here in upstream where there haven't been commits in months so I think it hasn't been fixed yet.

Maybe this could be fixed alongside #2, @toreanderson ?

**Comment by wcawijngaards** [comment]
The commit should solve your issue and writes the option to resolv.conf.  And also the edns0 option.  Only when resolv.conf is pointing at 127.0.0.1.

**Comment by alainwolf** [comment]
As described in resolv.conf(5), one can also set the **RES_OPTIONS** environment variable before running ssh. 

As a temporary workaround:
`RES_OPTIONS="edns0 trust-ad" ssh server.example.net`

Or for a more permanent temporary workaround ;)
`echo 'export RES_OPTIONS="edns0 trust-ad" ' >> ~/.profile`

**Comment by pabs3** [comment]
The commit above was not enough, this commit is also needed:

https://github.com/NLnetLabs/dnssec-trigger/commit/c8832f03158c04b20c6a08af2e914e02921e5e61

**Comment by omidraha** [comment]
What's `trust-ad` option in `/etc/resolv.conf` file?
```
options edns0 trust-ad
```

**Comment by pabs3** [comment]
Here is a copy of the documentation for this option:

   trust-ad (since glibc 2.31)
   
      Sets RES_TRUSTAD in _res.options. This option controls the AD bit
      behavior of the stub resolver. If a validating resolver sets the
      AD bit in a response, it indicates that the data in the response
      was verified according to the DNSSEC protocol. In order to rely
      on the AD bit, the local system has to trust both the DNSSEC
      validating resolver and the network path to it, which is why an
      explicit opt-in is required. If the trust-ad option is active,
      the stub resolver sets the AD bit in outgoing DNS queries (to
      enable AD bit support), and preserves the AD bit in responses.
      Without this option, the AD bit is not set in queries, and it is
      always removed from responses before they are returned to the
      application. This means that applications can trust the AD bit in
      responses if the trust-ad option has been set correctly.
      
      In glibc version 2.30 and earlier, the AD is not set
      automatically in queries, and is passed through unchanged to
      applications in responses.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by boyinblue** [comment]
> What's `trust-ad` option in `/etc/resolv.conf` file?
> 
> ```
> options edns0 trust-ad
> ```

The file is auto generated. So manual edit is not a permanent solution. 

``` cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
```
